### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by PKBeam** [PKBeam/Edda#3]
This is a list of features that have been requested by users.
This list will be updated over time as features are implemented or requested.

### 1.0.0 Release To-do
- [x] Export Map (to zip) option, removing backups
- [x] automatically set folder select dialog to Documents/Ragnarock song folder
- [x] proper version comparison for update checking
- [x] overhaul BPM change system
  - rename to "Timing change" to reduce confusion
  - add explicit support for setting the start of a song 
- [x] show BPM changes/bookmarks on grid waveform 
- [x] ~~right-click context menu~~ keyboard shortcut on grid waveform to create timing change or bookmark
- [ ] import externally made tempo map (as MIDI?)
- [x] move settings.txt to a shared program data folder

### Audio files
- [ ] Song file trimmer (to trim a song to begin on an integer beat)
- [X] BPM finding tool (v0.3.0b2)
- [X] A tool to generate the `preview.ogg` file from user-inputted timestamps (v0.4.0b1)

### Editor
- [x] Animation of drums during playback (v0.4.0b1)
- [ ] Auto-snap editor notes to waveform peaks
- [X] different drum samples for playback (v0.3.0b2)
- [X] variable BPM support (v0.3.0b1)
- [X] Use arrow keys to move note selections (v0.2.3)
- [X] Edit medal values (v0.2.3)
- [X] Select All (Ctrl-A) (v0.4.0b1)
- [X] Autosaving (v0.4.0b1) 
- [ ] Offset notes by a custom amount (beats or seconds)
- [ ] Option to automatically resnap notes on vBPM change
- [ ] Improve resolution of big waveform
- [x] Bookmarks (v0.4.0b1)
- [ ] Region syncing?
- [ ] Warn user of invisible double/stacked notes (on the same column)
- [X] Add notes as the song plays using keys (v0.4.0b1)
- [x] Variable speed playback of song (may not be possible with NAudio library?)  (v1.1.0b1)

### Map 
- [X] Feedback dialogs for file saving (v0.2.3)
- [x] A backup system for files
- [x] Ask to save when quitting

### Other
- [x] Discord Rich Presence support (v0.4.0b1)
- [ ] Ragnacustoms integration

**Comment by 4lex-Kidd** [comment]
> You can drag-select any off-grid notes to get rid of them.

Ah, thanks. Didn't know the runes are drag-able. My Bad.
